# Generated by Django 3.1.7 on 2021-03-09 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_das_receitas', models.CharField(max_length=100)),
                ('modo_de_preparo', models.TextField(max_length=300)),
                ('ingredientes', models.TextField()),
                ('tempo_de_preparo', models.CharField(max_length=100)),
                ('redimento', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
